create table person(
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) not null,
  age int not null,
  constraint pk_person primary key (id)
);

create sequence hibernate_sequence